import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class SettingsService with ChangeNotifier {
  bool _notificationsEnabled = false; // Default OFF as requested
  String _language = 'English';
  ThemeMode _themeMode = ThemeMode.dark;
  int _syncInterval = 10; // seconds
  bool _isSimulationMode = false; // Default to Live Firebase RTDB Mode

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _notificationsEnabled = prefs.getBool('notifications_enabled') ?? false;
    _language = prefs.getString('language') ?? 'English';
    _isSimulationMode = prefs.getBool('simulation_mode') ?? false;
    _syncInterval = prefs.getInt('sync_interval') ?? 10;
    
    final themeStr = prefs.getString('theme_mode') ?? 'dark';
    if (themeStr == 'light') {
      _themeMode = ThemeMode.light;
    } else if (themeStr == 'dark') {
      _themeMode = ThemeMode.dark;
    } else {
      _themeMode = ThemeMode.system;
    }
    notifyListeners();
  }

  final Map<String, Map<String, String>> _translations = {
    'English': {
      // Navigation
      'nav_dashboard': 'DASHBOARD',
      'nav_monitor': 'MONITOR',
      'nav_reports': 'REPORTS',
      'nav_profile': 'PROFILE',
      'dashboard': 'DASHBOARD',
      'monitor': 'MONITOR',
      'reports': 'REPORTS',
      'profile': 'PROFILE',

      // Common Actions & Tags
      'save': 'Save Changes',
      'close': 'Close',
      'cancel': 'CANCEL',
      'reset': 'Reset',
      'got_it': 'GOT IT',
      'understood': 'UNDERSTOOD',
      'latest': 'Latest',
      'safe': 'SAFE',
      'unsafe': 'UNSAFE',
      'optimal': 'Optimal',
      'attention': 'Attention',
      'score_upper': 'SCORE',
      'good_upper': 'GOOD',
      'fair_upper': 'FAIR',
      'poor_upper': 'POOR',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'system': 'System',
      'export_pdf': 'Export PDF',

      // Loading & Transitions
      'loading_system': 'Loading System...',
      'loading_dashboard': 'Loading Dashboard...',
      'syncing_telemetry': 'Synchronizing Sensor Telemetry...',
      'loading_reports': 'Loading Water Quality Reports...',
      'fetching_profile': 'Fetching Account Profile...',
      'checking_water_quality': 'Checking Water Quality...',
      'clean_water_motto': 'Clean Water  •  Healthier Tomorrow',
      'authenticating_account': 'Authenticating Account...',
      'init_local_stream': 'Initializing Local Stream...',
      'connecting_firebase': 'Connecting to Firebase Realtime Database...',

      // Login Screen
      'danum_monitor': 'Danum Monitor',
      'internal_use_only': 'INTERNAL USE ONLY',
      'login_subtitle': 'Sign in with your authorized internal account',
      'account_email': 'Account Email',
      'email_hint': 'user@example.com or test@example.com',
      'password': 'Password',
      'password_hint': 'Enter your password',
      'sign_in': 'SIGN IN',
      'login_footer_note': 'Restricted Access • Authorized User and Tester accounts only\nAccount details can be modified in the Profile section.',
      'err_fill_email_password': 'Please fill in both email and password',
      'err_access_denied': 'Access Denied: This application is for internal use only. Only the authorized User and Tester accounts can sign in.',
      'err_incorrect_password': 'Incorrect password. Please verify your credentials.',
      'err_weak_password': 'Password must be at least 6 characters.',
      'err_invalid_email': 'The email address is badly formatted.',
      'err_account_disabled': 'This internal account has been disabled.',
      'err_too_many_requests': 'Too many failed attempts. Please try again later.',
      'err_login_failed': 'Login failed. Please check credentials.',

      // Dashboard Header & Overview
      'water_quality': 'Water Quality',
      'live_analysis': 'Live Sensor Telemetry',
      'cloud_status': 'CLOUD CONNECT',
      'system_status': '3 SENSORS ONLINE',
      'current_metrics': 'Live Sensor Metrics',
      'dynamic_insights': 'AI Predictive Insights',
      'system_stable': 'System Nominal',
      'stable_msg': 'All 3 sensors (pH, TDS, Turbidity) indicate safe, clean drinking water.',
      'danum_title': 'DANUM',
      'simulated': 'SIMULATED',
      'firebase_live': 'FIREBASE LIVE',
      'sensors_chip_subtitle': 'pH • TDS • NTU',

      // Sensor Metrics Cards
      'ph_level': 'pH Level',
      'tds': 'TDS',
      'turbidity': 'Turbidity',
      'filter_health': 'Filter Health',
      'total_dissolved_solids': 'Total Dissolved Solids',
      'life_unit': 'Life',
      'ph_sub': 'Acidity level (6.5 - 8.5 is safe)',
      'tds_sub': 'Mineral pureness (< 600 ppm is safe)',
      'turb_sub': 'Water clarity (< 5 NTU is clear)',
      'safe_tag': 'SAFE TO DRINK',
      'moderate_tag': 'CHECK FILTER',
      'unsafe_tag': 'UNSAFE / FLUSH NEEDED',

      // Solenoid Valve Control
      'valve_control_title': 'SOLENOID VALVE CONTROL',
      'solenoid_valve': 'SOLENOID VALVE',
      'valve_status': 'VALVE STATUS',
      'valve_open': 'VALVE OPEN (Flow Active)',
      'valve_closed': 'VALVE CLOSED (Water Shut-off)',
      'mode': 'MODE',
      'auto_safety': 'AUTO SAFETY MODE',
      'manual_override': 'MANUAL OVERRIDE ACTIVE',
      'manual_override_active': 'Manual Override Active',
      'auto_cutoff_safe': 'Auto-Cutoff Active (Safe)',
      'auto_shutoff_unsafe': 'Auto-Shutoff (Unsafe Water)',
      'resume_auto': 'RESUME AUTO',
      'force_open_warning_title': 'UNSAFE WATER WARNING',
      'force_open_warning_body': 'The system detected that the water is currently NOT safe to consume:',
      'force_open_warning_confirm': 'Opening the valve will allow unsafe water to flow. Are you sure you want to force open the valve?',
      'force_open_confirm_btn': 'FORCE OPEN VALVE',

      // AI Filter Predictor
      'ai_predictor_title': 'AI FILTER REPLACEMENT PREDICTOR',
      'days_unit': 'Days',
      'days_short': 'd',
      'est_remaining': 'Est. Remaining',
      'filter_media_health': 'Filter Media Health',
      'baseline_drift_label': 'Baseline Drift',
      'drift_suffix': 'ppm/day drift',
      'remaining_lower': 'remaining',
      'flush_trigger_label': 'Flush Trigger',
      'required_immediately': 'REQUIRED IMMEDIATELY',
      'status_optimal': 'STATUS OPTIMAL',
      'spike_label': 'Spike',
      'safety_forecast_label': 'Safety Forecast',
      'window_label': 'Window',
      'ai_diagnosis_label': 'AI Diagnosis',
      'forecast_label': 'Forecast',
      'stress_breakdown_title': '3-SENSOR CLOGGING STRESS BREAKDOWN',
      'turbidity_stress_label': 'Turbidity Sediment Stress',
      'tds_stress_label': 'TDS Mineral Scaling Stress',
      'ph_stress_label': 'pH Chemical Stress',
      'stress_unit': 'Stress',

      // 5-Step Flushing Guide
      'view_flush_guide': 'VIEW FILTER REPLACEMENT STEPS',
      'guide_title': 'Filter Replacement Steps',
      'guide_subtitle': '5-step filter replacement & flushing procedure',
      'step1_title': 'Turn Off Faucet Valve',
      'step1_desc': 'Turn off the foset valve to stop incoming water flow.',
      'step2_title': 'Run Flushing Valve (3 Mins)',
      'step2_desc': 'Turn on the flushing valve, let it run for 3 minutes, then turn it off.',
      'step3_title': 'Close Pump Valve & Replace Filters',
      'step3_desc': 'Close the pump valve and replace all the filters with new ones.',
      'step4_title': 'Rinse Filters & Pipes (1-3 Mins)',
      'step4_desc': 'Open the flushing valve again to rinse the filters/pipes of any dirt remaining for 1-3 minutes, then close the valve again.',
      'step5_title': 'Resume Water Flow',
      'step5_desc': 'Resume the water flow of the foset valve.',
      'important_note': 'IMPORTANT NOTE',
      'flushing_note_desc': 'If the solenoid valve is not open, it means that the water is still dirty and may need to be flushed more until clean.',

      // Alerts & Notifications
      'system_alerts': 'System Alerts',
      'nominal_chip': 'NOMINAL',
      'active_chip': '{count} ACTIVE',
      'all_systems_nominal': 'All Systems Nominal',
      'no_active_alerts_desc': 'No active alerts. All 3 sensor metrics match standard healthy drinking conditions.',
      'alert_ph_acidic_title': 'Acidic pH Level',
      'alert_ph_acidic_body': 'pH is {value} (Too Acidic). Water may be corrosive and metallic.',
      'alert_ph_alkaline_title': 'Alkaline pH Level',
      'alert_ph_alkaline_body': 'pH is {value} (Too Alkaline). High scale-forming/mineral risk.',
      'alert_tds_high_title': 'High Dissolved Solids (TDS)',
      'alert_tds_high_body': 'TDS is {value} ppm. Dissolved mineral particles are elevated.',
      'alert_turb_high_title': 'High Water Turbidity',
      'alert_turb_high_body': 'Turbidity is {value} NTU (Cloudy). Higher sedimentation risk.',
      'alert_filter_replace_title': 'Filter Replacement Needed',
      'alert_filter_replace_body': 'Your filter health is at {value}%. Please replace filter soon.',
      'alert_unsafe_quality_title': '🔴 UNSAFE WATER QUALITY',
      'alert_unsafe_quality_body': 'Overall Score: {score}/100. Please check your water filter and source.',

      // Monitoring Screen
      'real_time_monitor': 'REAL-TIME MONITOR',
      'ph_trends': 'pH Level Trends (Acid/Alkaline)',
      'tds_trends': 'TDS Trends (Dissolved Minerals)',
      'turb_trends': 'Turbidity Trends (Water Clarity)',
      'stability': 'STABILITY',
      'avg_tds': 'AVG TDS',
      'max_turb': 'MAX TURB',
      'correlation_analysis': 'Correlation Analysis',
      'correlation_desc': 'This chart shows how different water metrics fluctuate together over time. For example, high turbidity often correlates with changes in TDS or pH levels due to suspended particles.',
      'sensor_log_archive': 'SENSOR LOG ARCHIVE',
      'tooltip_score_exp': 'Explain Water Quality Score',
      'tooltip_view_archive': 'View Log Archive',
      'tooltip_view_analysis': 'View Analysis',
      'device_uptime': 'SYSTEM STABILITY',
      'sensor_perf': 'Sensor Calibration & Health',
      'maintenance': 'Predictive Maintenance History',

      // Reports Screen
      'filter_today': 'Today',
      'filter_weekly': 'Weekly',
      'filter_monthly': 'Monthly',
      'filter_all': 'All',
      'select_date': 'Select Date',
      'filter_today_full': 'Today (Full Day)',
      'filter_past_7_days': 'Past 7 Days',
      'filter_past_30_days': 'Past 30 Days',
      'filter_all_records': 'All Historical Records',
      'filter_custom': 'Custom Filter',
      'records_count_suffix': 'records',
      'reset_filter_btn': 'Reset',
      'data_retention_notice': 'Data Retention Notice: Records older than 6 months (180 days) are automatically deleted to optimize database storage.',
      'tab_telemetry': 'Telemetry',
      'tab_audit_trail': 'Audit Trail',
      'raw_samples_count': 'RAW SAMPLES ({count} READINGS)',
      'session_batches_count': 'SESSION BATCHES ({count} SESSIONS)',
      'view_batches': 'View Batches',
      'view_raw_logs': 'View Raw Logs',
      'no_records_found': 'No Records Found',
      'no_records_desc': 'No data matches your selected date and time filter: {filter}',
      'reset_filter_full': 'Reset Filter',
      'compliance_summary_title': 'TELEMETRY COMPLIANCE SUMMARY',
      'pct_safe': '{pct}% SAFE',
      'safe_samples_summary': '{safe} of {total} sensor samples indicate safe drinking water.',
      'show_more_records': 'Show More Records ({remaining} remaining)',
      'tooltip_filter_date': 'Filter Date & Time',
      'tooltip_explain_score': 'Explain Quality Score',
      'tooltip_export_pdf': 'Export & Download PDF Report',
      'export_modal_title': 'Export & Report Generator',
      'export_modal_subtitle': 'Select data category and file format to print or download directly:',
      'telemetry_data': 'Telemetry Data ({count})',
      'audit_trail_data': 'Audit Trail ({count})',
      'all_dates_filtered': 'All Dates Filtered',
      'change_date': 'Change Date',
      'pdf_export_options': 'PDF EXPORT OPTIONS ({count} records)',
      'download_save_pdf': 'Download / Save PDF ({target})',
      'print_pdf': 'Print PDF ({target})',
      'report_summary_title': 'AVERAGED REPORT SUMMARY',
      'quality_score_title': 'QUALITY SCORE',
      'averaged_metrics_title': 'AVERAGED SENSOR METRICS',
      'system_status_title': 'SYSTEM & ACTUATOR STATUS',
      'raw_samples_title': 'RAW SENSOR SAMPLES INCLUDED',
      'show_more_logs': 'SHOW MORE LOGS',
      'monthly_overview': 'MONTHLY OVERVIEW',
      'system_perf': '3-SENSOR PERFORMANCE',
      'score': 'Score',
      'avg_monthly_quality': 'Average Monthly Quality',
      'avg_weekly_quality': 'Average Weekly Quality',

      // Profile Screen
      'account_settings': 'ACCOUNT SETTINGS',
      'general_settings': 'General Settings',
      'notifications': 'Alert Notifications',
      'theme_mode': 'App Theme',
      'language': 'Language',
      'sys_prefs': 'Data Refresh Preferences',
      'sync_interval': 'Cloud Sync Rate',
      'enter_name': 'Enter Name',
      'email_address': 'Email Address',
      'old_password': 'Old Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'update_credentials': 'Update Credentials',
      'cancel_btn': 'Cancel',
      'save_changes_btn': 'Save Changes',
      'logout': 'LOGOUT',
      'old_pw_required': 'Old password is required',
      'new_pw_empty': 'New password cannot be empty',
      'pw_not_match': 'Passwords do not match',
      'profile_updated': 'Profile updated: {name}',
      'account_updated_success': 'Account updated successfully',
      'notifications_enabled_toast': 'Notifications enabled successfully!',
      'notifications_denied_toast': 'Notification permission denied by system.',
      'theme_dark': 'Dark',
      'theme_light': 'Light',
      'cloud_sync_lifetime_title': 'Cloud Sync Rate & Database Lifetime',
      'cloud_sync_lifetime_desc': '• How It Works:\nControls how frequently the system uploads real-time water quality sensor metrics (pH, TDS, turbidity, battery) to the cloud database.\n\n• Impact on Database Lifetime & Quotas:\n• Faster Sync (10s): Provides near-instant telemetry updates and faster emergency alerting, but generates high write traffic, consumes more bandwidth and power, and reaches cloud database storage quotas sooner.\n• Slower Sync (30s–60s): Minimizes write frequency, significantly reduces database size accumulation, prevents quota exhaustion, and dramatically extends database lifetime while preserving reliable monitoring.',
      'app_repo_title': 'APP & REPOSITORY',
      'app_version': 'Version 1.0.1 (Build 2)',
      'github_repo_btn': 'GitHub Repo',
      'download_apk_btn': 'Download APK',
      'image_upload_soon': 'Image upload coming soon',

      // Solar Power
      'solar_power': 'Solar Power',
      'battery_voltage_output': 'Battery Voltage Output',
      'solar_charging': 'Charging',
      'solar_normal': 'Normal',
      'solar_low_battery': 'Low Battery',

      // UI Helpers / Educational Tooltips
      'need_to_know': 'NEED TO KNOW',
      'safe_threshold': 'Safe Threshold:',
      'score_explanation_title': 'WATER QUALITY SCORE',
      'score_index_subtitle': '0 to 100 Safety & Purity Index',
      'base_target_100': 'Base Target: 100 Points',
      'score_explanation_body': 'The score starts at 100 for ideal water. Deductions are calculated automatically from 3 telemetry sensors:',
      'rule_ph_title': '1. pH Deviation',
      'rule_ph_desc': '-15 pts per 1.0 pH away from 7.0 (Ideal: 6.5–8.5)',
      'rule_tds_title': '2. TDS Mineral Scaling',
      'rule_tds_desc': '-0.1 pts per 1 ppm over 50 ppm (Ideal: < 600 ppm)',
      'rule_turb_title': '3. Turbidity Cloudiness',
      'rule_turb_desc': '-10 pts per 1.0 NTU over 1.0 NTU (Ideal: < 5.0 NTU)',
      'status_tiers': 'STATUS TIERS',
      'tier_good_title': 'GOOD / SAFE',
      'tier_good_desc': 'Water is clean & safe to consume.',
      'tier_fair_title': 'FAIR / WARNING',
      'tier_fair_desc': 'Acceptable but approaching safety thresholds.',
      'tier_poor_title': 'POOR / UNSAFE',
      'tier_poor_desc': 'Unsafe water! Automatic solenoid cut-off active.',
      'ph_info': 'The safe range for drinking water is between 6.5 and 8.5. pH levels outside this range can indicate chemical contamination or lead to pipe corrosion.',
      'tds_info': 'TDS represents the amount of minerals, salts, or metals dissolved in water. Levels below 600 ppm are generally considered safe and palatable.',
      'turb_info': 'Turbidity measures the cloudiness of water. High turbidity can protect bacteria from disinfection and often indicates high particle content.',
      'score_info': 'Overall water safety score computed dynamically from pH, TDS, and Turbidity 3-sensor telemetry.',
    },

    'Tagalog': {
      // Navigation
      'nav_dashboard': 'HOME',
      'nav_monitor': 'MONITOR',
      'nav_reports': 'ULAT',
      'nav_profile': 'PROFILE',
      'dashboard': 'PANGUNAHING PAHINA',
      'monitor': 'MONITORING',
      'reports': 'MGA ULAT',
      'profile': 'PROFILE',

      // Common Actions & Tags
      'save': 'I-save ang Pagbabago',
      'close': 'Isara',
      'cancel': 'KANSELAHIN',
      'reset': 'I-reset',
      'got_it': 'NAINTINDIHAN KO',
      'understood': 'NAUNAWAAN',
      'latest': 'Pinakabago',
      'safe': 'LIGTAS',
      'unsafe': 'HINDI LIGTAS',
      'optimal': 'Maayos',
      'attention': 'Pansinin',
      'score_upper': 'PUNTOS',
      'good_upper': 'MABUTI',
      'fair_upper': 'KATAMTAMAN',
      'poor_upper': 'HINDI LIGTAS',
      'weekly': 'Lingguhan',
      'monthly': 'Buwanan',
      'system': 'Sistema',
      'export_pdf': 'I-download ang PDF',

      // Loading & Transitions
      'loading_system': 'Ikinakarga ang Sistema...',
      'loading_dashboard': 'Ikinakarga ang Pangunahing Pahina...',
      'syncing_telemetry': 'Ipinagsasabay ang mga Sukat ng Sensor...',
      'loading_reports': 'Ikinakarga ang mga Ulat ng Kalidad...',
      'fetching_profile': 'Kinukuha ang Profile ng Akawnt...',
      'checking_water_quality': 'Sinusuri ang Kalidad ng Tubig...',
      'clean_water_motto': 'Malinis na Tubig  •  Mas Malusog na Bukas',
      'authenticating_account': 'Pinatutunayan ang Akawnt...',
      'init_local_stream': 'Sinisimulan ang Lokal na Daloy...',
      'connecting_firebase': 'Kumukonekta sa Firebase Database...',

      // Login Screen
      'danum_monitor': 'Danum Monitor',
      'internal_use_only': 'PARA SA PANLOOB NA GAMIT LAMANG',
      'login_subtitle': 'Mag-sign in gamit ang iyong awtorisadong panloob na account',
      'account_email': 'Email ng Akawnt',
      'email_hint': 'user@example.com o test@example.com',
      'password': 'Password',
      'password_hint': 'Ilagay ang iyong password',
      'sign_in': 'MAG-SIGN IN',
      'login_footer_note': 'Limitadong Akses • Para lamang sa mga Awtorisadong User at Tester\nAng mga detalye ng akawnt ay maaaring baguhin sa seksyon ng Profile.',
      'err_fill_email_password': 'Pakiusap ilagay ang parehong email at password',
      'err_access_denied': 'Tinanggihan ang Akses: Ang application na ito ay para sa panloob na gamit lamang. Ang mga awtorisadong User at Tester account lamang ang maaaring mag-sign in.',
      'err_incorrect_password': 'Maling password. Pakiusap suriin ang iyong mga kredensyal.',
      'err_weak_password': 'Ang password ay dapat hindi bababa sa 6 na karakter.',
      'err_invalid_email': 'Mali ang pormat ng email address.',
      'err_account_disabled': 'Ang panloob na account na ito ay hindi pinagana.',
      'err_too_many_requests': 'Masyadong maraming nabigong pagsubok. Pakiusap subukan muli mamaya.',
      'err_login_failed': 'Bumagsak ang pag-login. Pakiusap suriin ang iyong kredensyal.',

      // Dashboard Header & Overview
      'water_quality': 'Kalidad ng Tubig',
      'live_analysis': 'Kasalukuyang Sukat sa Cloud',
      'cloud_status': 'KONEKSYON SA CLOUD',
      'system_status': '3 SENSOR GUMAGANA',
      'current_metrics': 'Mga Sukat ng Sensor Ngayon',
      'dynamic_insights': 'AI Pagsusuri at Payo',
      'system_stable': 'Maayos at Ligtas ang Tubig',
      'stable_msg': 'Lahat ng 3 sukat (pH, TDS, Turbidity) ay malinis at ligtas inumin.',
      'danum_title': 'DANUM',
      'simulated': 'SIMULASYON',
      'firebase_live': 'FIREBASE LIVE',
      'sensors_chip_subtitle': 'pH • TDS • NTU',

      // Sensor Metrics Cards
      'ph_level': 'Antas ng pH',
      'tds': 'TDS',
      'turbidity': 'Linaw ng Tubig',
      'filter_health': 'Buhay ng Filter',
      'total_dissolved_solids': 'Dami ng Natunaw na Mineral (TDS)',
      'life_unit': 'Buhay',
      'ph_sub': 'Antas ng asim (Ligtas kung 6.5 - 8.5)',
      'tds_sub': 'Dami ng mineral (Ligtas kapag mas mababa sa 600 ppm)',
      'turb_sub': 'Linaw ng tubig (Ligtas kapag malinis at mas mababa sa 5 NTU)',
      'safe_tag': 'MALINIS AT LIGTAS INUMIN',
      'moderate_tag': 'KATAMTAMAN / I-TSITSEK ANG PILTRO',
      'unsafe_tag': 'HINDI LIGTAS / KAILANGAN BANLAWAN',

      // Solenoid Valve Control
      'valve_control_title': 'KONTROL NG BALBULA NG TUBIG',
      'solenoid_valve': 'BALBULA NG TUBIG',
      'valve_status': 'KALAGAYAN NG BALBULA',
      'valve_open': 'NAKABUKAS (BUMAGOS ANG TUBIG)',
      'valve_closed': 'NAKASARA (PINIGILAN ANG TUBIG)',
      'mode': 'PARAAN NG KONTROL',
      'auto_safety': 'AUTOMATIC NA LIGTAS',
      'manual_override': 'SARILING KONTROL GAMIT',
      'manual_override_active': 'Sariling Kontrol Gamit',
      'auto_cutoff_safe': 'Awtomatikong Proteksyon (Ligtas)',
      'auto_shutoff_unsafe': 'Awtomatikong Isinara (Hindi Ligtas)',
      'resume_auto': 'BUMALIK SA AUTOMATIC',
      'force_open_warning_title': 'BABALA: HINDI LIGTAS ANG TUBIG',
      'force_open_warning_body': 'Natuklasan ng sistema na ang tubig ay HINDI ligtas inumin ngayon:',
      'force_open_warning_confirm': 'Ang pagbukas ng balbula ay magpapadaloy ng maruming tubig. Sigurado ka bang nais mong piliting buksan ang balbula?',
      'force_open_confirm_btn': 'PILITIN IBUKAS ANG BALBULA',

      // AI Filter Predictor
      'ai_predictor_title': 'AI TAGAPAGSURI NG PAGPAPALIT NG FILTER',
      'days_unit': 'Araw',
      'days_short': 'a',
      'est_remaining': 'Tinatayang Natitira',
      'filter_media_health': 'Kalusugan ng Filter Media',
      'baseline_drift_label': 'Pagbabago ng Baseline',
      'drift_suffix': 'ppm/araw pagbabago',
      'remaining_lower': 'natitira',
      'flush_trigger_label': 'Hudyat sa Pagbanlaw',
      'required_immediately': 'KAILANGAN AGAD',
      'status_optimal': 'MAAYOS ANG KALAGAYAN',
      'spike_label': 'Biglang Taas',
      'safety_forecast_label': 'Pagtataya sa Kaligtasan',
      'window_label': 'Oras',
      'ai_diagnosis_label': 'AI Pagsusuri',
      'forecast_label': 'Pagtataya',
      'stress_breakdown_title': 'PAGSUSURI NG BARA AT STRESS SA 3 SENSOR',
      'turbidity_stress_label': 'Stress sa Latak at Labo (Turbidity)',
      'tds_stress_label': 'Stress sa Dami ng Mineral (TDS)',
      'ph_stress_label': 'Stress sa Asim o Asido (pH)',
      'stress_unit': 'Stress',

      // 5-Step Flushing Guide
      'view_flush_guide': 'MGA HAKBANG SA PAGPAPALIT NG FILTER',
      'guide_title': 'Mga Hakbang sa Pagpapalit ng Filter',
      'guide_subtitle': 'Limang hakbang sa pagpapalit at pagbanlaw ng filter',
      'step1_title': 'Isara ang Balbula ng Gripo',
      'step1_desc': 'Isara ang balbula ng gripo upang mapigil ang daloy ng tubig papasok.',
      'step2_title': 'Buksan ang Balbula ng Pagbanlaw (3 Minuto)',
      'step2_desc': 'Buksan ang balbula ng pagbanlaw, hayaang tumakbo nang 3 minuto, pagkatapos ay isara ito.',
      'step3_title': 'Isara ang Balbula ng Bomba at Palitan ang mga Filter',
      'step3_desc': 'Isara ang balbula ng bomba at palitan ang lahat ng filter ng mga bago.',
      'step4_title': 'Banlawan ang mga Filter at Tubo (1-3 Minuto)',
      'step4_desc': 'Buksan muli ang balbula ng pagbanlaw upang banlawan ang dumi sa filter at tubo sa loob ng 1-3 minuto, pagkatapos ay isara muli.',
      'step5_title': 'Ibalik ang Daloy ng Tubig',
      'step5_desc': 'Ibalik ang normal na daloy ng tubig sa balbula ng gripo.',
      'important_note': 'MAHALAGANG PAALALA',
      'flushing_note_desc': 'Kung ang balbula ay hindi nakabukas, nangangahulugang marumi pa ang tubig at kailangang banlawan pa hanggang sa luminis.',

      // Alerts & Notifications
      'system_alerts': 'Mga Babala ng Sistema',
      'nominal_chip': 'NORMAL',
      'active_chip': '{count} AKTIBO',
      'all_systems_nominal': 'Lahat ng Sistema ay Maayos',
      'no_active_alerts_desc': 'Walang aktibong babala. Ang lahat ng 3 sukat ng sensor ay tugma sa pamantayan ng malinis na inuming tubig.',
      'alert_ph_acidic_title': 'Masyadong Maasim ang Tubig (Acidic pH)',
      'alert_ph_acidic_body': 'Ang pH ay {value} (Masyadong Maasim). Ang tubig ay maaaring makalawang at may lasang metal.',
      'alert_ph_alkaline_title': 'Masyadong Matabang/Alkaline ang Tubig',
      'alert_ph_alkaline_body': 'Ang pH ay {value} (Masyadong Alkaline). Mataas ang peligro ng namumuong mineral sa tubo.',
      'alert_tds_high_title': 'Mataas ang Dissolved Solids (TDS)',
      'alert_tds_high_body': 'Ang TDS ay {value} ppm. Mataas ang dami ng natunaw na mineral sa tubig.',
      'alert_turb_high_title': 'Malabo ang Tubig (High Turbidity)',
      'alert_turb_high_body': 'Ang linaw ay {value} NTU (Malabo). Mataas ang peligro ng putik o latak sa tubig.',
      'alert_filter_replace_title': 'Kailangang Palitan ang Filter',
      'alert_filter_replace_body': 'Ang kalusugan ng iyong filter ay nasa {value}%. Pakiusap palitan na ito agad.',
      'alert_unsafe_quality_title': '🔴 HINDI LIGTAS ANG KALIDAD NG TUBIG',
      'alert_unsafe_quality_body': 'Kabuuang Puntos: {score}/100. Pakiusap suriin ang iyong filter at pinagmumulan ng tubig.',

      // Monitoring Screen
      'real_time_monitor': 'MONITORING NGAYON',
      'ph_trends': 'Antas ng pH (Asim ng Tubig)',
      'tds_trends': 'Antas ng TDS (Dami ng Mineral)',
      'turb_trends': 'Antas ng Turbidity (Linaw ng Tubig)',
      'stability': 'TATAG',
      'avg_tds': 'KARANIWANG TDS',
      'max_turb': 'PINAKAMALABO',
      'correlation_analysis': 'Pagsusuri ng Pagkakaugnay',
      'correlation_desc': 'Ipinapakita ng tsart na ito kung paano magkasabay na nagbabago ang mga sukat ng tubig. Halimbawa, ang mataas na labo ay madalas nauugnay sa pagbabago ng TDS o pH dahil sa mga dumi sa tubig.',
      'sensor_log_archive': 'KASAYSAYAN NG MGA SUKAT',
      'tooltip_score_exp': 'Ipaliwanag ang Puntos ng Tubig',
      'tooltip_view_archive': 'Tingnan ang Kasaysayan',
      'tooltip_view_analysis': 'Tingnan ang Pagsusuri',
      'device_uptime': 'TATAG NG SISTEMA',
      'sensor_perf': 'Kalagayan ng 3 Sensor',
      'maintenance': 'Kasaysayan ng Pagbanlaw',

      // Reports Screen
      'filter_today': 'Ngayon',
      'filter_weekly': 'Lingguhan',
      'filter_monthly': 'Buwanan',
      'filter_all': 'Lahat',
      'select_date': 'Pumili ng Petsa',
      'filter_today_full': 'Ngayon (Buong Araw)',
      'filter_past_7_days': 'Nakalipas na 7 Araw',
      'filter_past_30_days': 'Nakalipas na 30 Araw',
      'filter_all_records': 'Lahat ng Nakaraang Rekord',
      'filter_custom': 'Pasadyang Salain',
      'records_count_suffix': 'mga rekord',
      'reset_filter_btn': 'I-reset',
      'data_retention_notice': 'Abiso sa Pagpapanatili ng Datos: Ang mga rekord na higit sa 6 na buwan (180 araw) ay awtomatikong binubura upang mapanatiling mabilis ang database.',
      'tab_telemetry': 'Sukat ng Sensor',
      'tab_audit_trail': 'Kasaysayan ng Aksyon',
      'raw_samples_count': 'MGA ISAHANG SUKAT ({count} BASA)',
      'session_batches_count': 'MGA GRUPO NG SUKAT ({count} SESYON)',
      'view_batches': 'Tingnan ang Grupo',
      'view_raw_logs': 'Tingnan ang Isahang Log',
      'no_records_found': 'Walang Nahanap na Rekord',
      'no_records_desc': 'Walang datos na tumutugma sa napiling petsa at oras: {filter}',
      'reset_filter_full': 'I-reset ang Filter',
      'compliance_summary_title': 'BUOD NG PAGSUNOD SA KALINISAN',
      'pct_safe': '{pct}% LIGTAS',
      'safe_samples_summary': '{safe} sa {total} na sukat ng sensor ay nagpapatunay na ligtas ang inuming tubig.',
      'show_more_records': 'Ipakita ang Iba Pang Rekord ({remaining} natitira)',
      'tooltip_filter_date': 'Salain ang Petsa at Oras',
      'tooltip_explain_score': 'Ipaliwanag ang Puntos ng Kalidad',
      'tooltip_export_pdf': 'I-export at I-download ang PDF na Ulat',
      'export_modal_title': 'Tagagawa ng Ulat at Pag-export',
      'export_modal_subtitle': 'Pumili ng kategorya ng datos at format ng file upang i-print o i-download:',
      'telemetry_data': 'Datos ng Sensor ({count})',
      'audit_trail_data': 'Kasaysayan ng Aksyon ({count})',
      'all_dates_filtered': 'Lahat ng Petsa',
      'change_date': 'Baguhin ang Petsa',
      'pdf_export_options': 'MGA OPSYON SA PAG-DOWNLOAD NG PDF ({count} rekord)',
      'download_save_pdf': 'I-download / I-save ang PDF ({target})',
      'print_pdf': 'I-print ang PDF ({target})',
      'report_summary_title': 'BUOD NG ULAT NG TUBIG',
      'quality_score_title': 'PUNTOS NG KALIDAD',
      'averaged_metrics_title': 'KATAMTAMANG SUKAT NG SENSOR',
      'system_status_title': 'KALAGAYAN NG PILTRO AT BALBULA',
      'raw_samples_title': 'MGA SUKAT NA ISINAMA',
      'show_more_logs': 'IPAKITA ANG IBA PANG ULAT',
      'monthly_overview': 'BUWANANG ULAT',
      'system_perf': 'PERFORMANCE NG 3 SENSOR',
      'score': 'Puntos',
      'avg_monthly_quality': 'Karaniwang Kalidad (Buwan)',
      'avg_weekly_quality': 'Karaniwang Kalidad (Linggo)',

      // Profile Screen
      'account_settings': 'SETTINGS NG AKOUNT',
      'general_settings': 'Settings ng App',
      'notifications': 'Mga Notipikasyon at Babala',
      'theme_mode': 'Kulay ng App (Theme)',
      'language': 'Wika / Salita',
      'sys_prefs': 'Settings ng Sistema',
      'sync_interval': 'Bilis ng Pag-update',
      'enter_name': 'Ilagay ang Pangalan',
      'email_address': 'Email Address',
      'old_password': 'Lumang Password',
      'new_password': 'Bagong Password',
      'confirm_new_password': 'Kumpirmahin ang Bagong Password',
      'update_credentials': 'Baguhin ang Password',
      'cancel_btn': 'Kanselahin',
      'save_changes_btn': 'I-save ang Pagbabago',
      'logout': 'MAG-LOGOUT',
      'old_pw_required': 'Kailangan ang lumang password',
      'new_pw_empty': 'Hindi maaaring walang laman ang bagong password',
      'pw_not_match': 'Hindi magkatugma ang password',
      'profile_updated': 'Na-update ang profile: {name}',
      'account_updated_success': 'Matagumpay na na-update ang akawnt',
      'notifications_enabled_toast': 'Matagumpay na binuksan ang mga notipikasyon!',
      'notifications_denied_toast': 'Tinanggihan ng sistema ang pahintulot sa notipikasyon.',
      'theme_dark': 'Madilim (Dark)',
      'theme_light': 'Maliwanag (Light)',
      'cloud_sync_lifetime_title': 'Bilis ng Pag-sync sa Cloud at Tagal ng Database',
      'cloud_sync_lifetime_desc': '• Paano Ito Gumagana:\nKinokontrol kung gaano kadalas ina-upload ng sistema ang mga sukat ng kalidad ng tubig (pH, TDS, labo, baterya) sa cloud database.\n\n• Epekto sa Buhay ng Database at Quotas:\n• Mas Mabilis na Sync (10s): Nagbibigay ng halos agarang mga sukat at mabilis na babala sa oras ng peligro, ngunit kumokonsumo ng mas maraming bandwidth at kuryente, at mas mabilis mapuno ang libreng imbakan ng database.\n• Mas Mabagal na Sync (30s–60s): Nagpapababa ng dalas ng pagsulat, lubos na nagpapabagal sa paglaki ng database, naiiwasan ang pagkaubos ng quota, at pinahahaba ang buhay ng database habang nananatiling maaasahan ang pagsubaybay.',
      'app_repo_title': 'IMPORMASYON NG APP',
      'app_version': 'Bersyon 1.0.1 (Build 2)',
      'github_repo_btn': 'GitHub Repo',
      'download_apk_btn': 'I-download ang APK',
      'image_upload_soon': 'Paparating na ang pag-upload ng imahe',

      // Solar Power
      'solar_power': 'Lakas ng Araw (Solar)',
      'battery_voltage_output': 'Bentahe ng Baterya',
      'solar_charging': 'Nagkakarga',
      'solar_normal': 'Normal',
      'solar_low_battery': 'Mahinang Baterya',

      // UI Helpers / Educational Tooltips
      'need_to_know': 'DAPAT MALAMAN',
      'safe_threshold': 'Ligtas na Antas:',
      'score_explanation_title': 'PUNTOS NG KALIDAD NG TUBIG',
      'score_index_subtitle': '0 hanggang 100 Index ng Kaligtasan at Kalinisan',
      'base_target_100': 'Pangunahing Puntos: 100 Puntos',
      'score_explanation_body': 'Nagsisimula sa 100 ang puntos para sa perpektong tubig. Ang bawas ay kinakalkula nang awtomatiko mula sa 3 sensor:',
      'rule_ph_title': '1. Paglihis ng pH',
      'rule_ph_desc': '-15 puntos kada 1.0 pH layo sa 7.0 (Perpekto: 6.5–8.5)',
      'rule_tds_title': '2. Dami ng Mineral sa TDS',
      'rule_tds_desc': '-0.1 puntos kada 1 ppm higit sa 50 ppm (Perpekto: < 600 ppm)',
      'rule_turb_title': '3. Labo ng Tubig (Turbidity)',
      'rule_turb_desc': '-10 puntos kada 1.0 NTU higit sa 1.0 NTU (Perpekto: < 5.0 NTU)',
      'status_tiers': 'MGA ANTAS NG KALIDAD',
      'tier_good_title': 'MABUTI / LIGTAS',
      'tier_good_desc': 'Malinis at ligtas inumin ang tubig.',
      'tier_fair_title': 'KATAMTAMAN / MAG-INGAT',
      'tier_fair_desc': 'Katanggap-tanggap ngunit papalapit na sa hangganan ng kaligtasan.',
      'tier_poor_title': 'HINDI LIGTAS / DELIKADO',
      'tier_poor_desc': 'Hindi ligtas ang tubig! Awtomatikong pinutol ang daloy gamit ang balbula.',
      'ph_info': 'Ang ligtas na antas ng pH para sa inuming tubig ay nasa pagitan ng 6.5 at 8.5. Ang mga antas sa labas nito ay maaaring magpahiwatig ng kontaminasyon ng kemikal o makalawang sa mga tubo.',
      'tds_info': 'Kinakatawan ng TDS ang dami ng mga mineral, asin, o metal na natunaw sa tubig. Ang mga antas na mas mababa sa 600 ppm ay karaniwang ligtas at masarap inumin.',
      'turb_info': 'Sinusukat ng turbidity ang linaw o labo ng tubig. Ang mataas na labo ay maaaring magkanlong ng bakterya at nagpapahiwatig ng mga dumi o putik sa tubig.',
      'score_info': 'Kabuuang puntos ng kaligtasan ng tubig na kinakalkula mula sa mga sukat ng pH, TDS, at Turbidity sensors.',
    },

    'Kapampangan': {
      // Navigation
      'nav_dashboard': 'HOME',
      'nav_monitor': 'MONITOR',
      'nav_reports': 'ULAT',
      'nav_profile': 'PROFILE',
      'dashboard': 'PANGUNAHING PAHINA',
      'monitor': 'PAMANALANSAG',
      'reports': 'MGA ULAT',
      'profile': 'PROFILE',

      // Common Actions & Tags
      'save': 'I-save reng Pamagbayu',
      'close': 'Isara',
      'cancel': 'KANSELAHIN',
      'reset': 'I-reset',
      'got_it': 'ABALU KU',
      'understood': 'AINTINDIAN KU',
      'latest': 'Pekabayung Bersyun',
      'safe': 'LIGTAS',
      'unsafe': 'E LIGTAS',
      'optimal': 'Masalese',
      'attention': 'Pansinan',
      'score_upper': 'PUNTOS',
      'good_upper': 'MAYAP',
      'fair_upper': 'KATAMTAMAN',
      'poor_upper': 'E LIGTAS',
      'weekly': 'Paruminggu',
      'monthly': 'Babuwan',
      'system': 'Sistema',
      'export_pdf': 'I-download ing PDF',

      // Loading & Transitions
      'loading_system': 'Pangarga ing Sistema...',
      'loading_dashboard': 'Pangarga ing Pangunahing Pahina...',
      'syncing_telemetry': 'Pisasabay la reng Sukat ning Sensor...',
      'loading_reports': 'Pangarga la reng Ulat ning Kalidad...',
      'fetching_profile': 'Kukwa ya ing Profile ning Akawnt...',
      'checking_water_quality': 'Susuryan ing Kalidad ning Danum...',
      'clean_water_motto': 'Malinis a Danum  •  Mas Masalunat a Bukas',
      'authenticating_account': 'Papatutuan ya ing Akawnt...',
      'init_local_stream': 'Papasimulan ing Lokal a Agos...',
      'connecting_firebase': 'Makikonekta king Firebase Database...',

      // Login Screen
      'danum_monitor': 'Danum Monitor',
      'internal_use_only': 'PARA KENG PANGKILUB A GAMIT NAMU',
      'login_subtitle': 'Mag-sign in gamit ing kekang awtorisadung pangkilub a akawnt',
      'account_email': 'Email ning Akawnt',
      'email_hint': 'user@example.com o test@example.com',
      'password': 'Password',
      'password_hint': 'Isulat ing kekang password',
      'sign_in': 'MAG-SIGN IN',
      'login_footer_note': 'Limitadung Akses • Para mu kareng Awtorisadung User at Tester\nDing detalye ning akawnt maliari lang bayuan king dake ning Profile.',
      'err_fill_email_password': 'Pakisulat parehu ing email ampo password',
      'err_access_denied': 'Mitanggi ing Akses: Ing application ayni para mu keng pangkilub a gamit. Ding awtorisadung User ampo Tester akawnt mu reng maliaring mag-sign in.',
      'err_incorrect_password': 'Maling password. Pakisuri pasibayu ing kekang kredensyal.',
      'err_weak_password': 'Ing password dapat e ya lalam king 6 a letra.',
      'err_invalid_email': 'Mali ya pormat ing email address.',
      'err_account_disabled': 'Ing pangkilub a akawnt ayni me-disable ya.',
      'err_too_many_requests': 'Masyadung dakal a mebigung subuk. Pakisubukan pasibayu potang mangatwa.',
      'err_login_failed': 'Mebigu ing pamag-login. Pakisuri ing kekang kredensyal.',

      // Dashboard Header & Overview
      'water_quality': 'Kalidad ning Danum',
      'live_analysis': 'Sukat ngeni king Cloud',
      'cloud_status': 'KONEKSYON KING CLOUD',
      'system_status': '3 SENSOR TITIPA',
      'current_metrics': 'Sukat ning Sensor Ngeni',
      'dynamic_insights': 'AI Kabaluan at Payu',
      'system_stable': 'Masalese at Ligtas ing Danum',
      'stable_msg': 'Eganaganang 3 sukat (pH, TDS, Turbidity) malinis at ligtas inuman.',
      'danum_title': 'DANUM',
      'simulated': 'SIMULASYUN',
      'firebase_live': 'FIREBASE LIVE',
      'sensors_chip_subtitle': 'pH • TDS • NTU',

      // Sensor Metrics Cards
      'ph_level': 'Lebel ning pH',
      'tds': 'TDS',
      'turbidity': 'Linaw ning Danum',
      'filter_health': 'Bie ning Filtro',
      'total_dissolved_solids': 'Kabilugan ding Mitunaw a Mineral (TDS)',
      'life_unit': 'Bie',
      'ph_sub': 'Lebel ning aslam (Ligtas nung 6.5 - 8.5)',
      'tds_sub': 'Karakal ning mineral (Ligtas nung mababa king 600 ppm)',
      'turb_sub': 'Linaw ning danum (Ligtas nung malinis at mababa king 5 NTU)',
      'safe_tag': 'MALINIS AT LIGTAS INUMAN',
      'moderate_tag': 'KATAMTAMAN / SURIAN ING FILTRO',
      'unsafe_tag': 'E LIGTAS / KAILANGAN PAMLUSAYAN',

      // Solenoid Valve Control
      'valve_control_title': 'KONTROL NING BALBULA NING DANUM',
      'solenoid_valve': 'BALBULA NING DANUM',
      'valve_status': 'KALAGAYAN NING BALBULA',
      'valve_open': 'NAKABUKAS (TITIPUS ING DANUM)',
      'valve_closed': 'NAKASARA (PETIKAN ING DANUM)',
      'mode': 'PARAAN NING KONTROL',
      'auto_safety': 'AUTOMATIC A LIGTAS',
      'manual_override': 'SARILING KONTROL GAMIT',
      'manual_override_active': 'Sariling Kontrol Gamit',
      'auto_cutoff_safe': 'Awtomatikong Proteksyon (Ligtas)',
      'auto_shutoff_unsafe': 'Awtomatikong Isinara (E Ligtas)',
      'resume_auto': 'MAGBALIK SA AUTOMATIC',
      'force_open_warning_title': 'BABALA: E LIGTAS ING DANUM',
      'force_open_warning_body': 'Atuklasan ning sistema a ing danum E ya ligtas inuman ngeni:',
      'force_open_warning_confirm': 'Ing pamuklat king balbula papagusan ne ing e ligtas a danum. Siguradu ka bang bisang pilitan yang buklat ing balbula?',
      'force_open_confirm_btn': 'PILITIN IBUKAS ING BALBULA',

      // AI Filter Predictor
      'ai_predictor_title': 'AI TAGAPANGSURI NING PAMAGBAYUNG FILTER',
      'days_unit': 'Aldo',
      'days_short': 'a',
      'est_remaining': 'Tinatayang Matitagan',
      'filter_media_health': 'Kalusugan ning Filter Media',
      'baseline_drift_label': 'Pamagbayu ning Baseline',
      'drift_suffix': 'ppm/aldo pamagbayu',
      'remaining_lower': 'matitagan',
      'flush_trigger_label': 'Senyal king Pamilis',
      'required_immediately': 'KAILANGAN KAKALALE',
      'status_optimal': 'MASALESE ING KALAGAYAN',
      'spike_label': 'Biglang Tas',
      'safety_forecast_label': 'Pagtataya king Kaligtasan',
      'window_label': 'Oras',
      'ai_diagnosis_label': 'AI Pamusuri',
      'forecast_label': 'Pagtataya',
      'stress_breakdown_title': 'PAMUSURI KING BARA AT STRESS KARENG 3 SENSOR',
      'turbidity_stress_label': 'Stress king Latak at Labo (Turbidity)',
      'tds_stress_label': 'Stress king Karakal ning Mineral (TDS)',
      'ph_stress_label': 'Stress king Aslam ning Danum (pH)',
      'stress_unit': 'Stress',

      // 5-Step Flushing Guide
      'view_flush_guide': 'DENG HAKBANG KING PAMAGBAYUNG FILTER',
      'guide_title': 'Deng Hakbang king Pamagbayung Filter',
      'guide_subtitle': 'Limang hakbang king pamagbayu at pamamalis king filtro',
      'step1_title': 'Isara ing Balbula ning Gripo',
      'step1_desc': 'Isara ing balbula ning gripo bang mapigil ing agus ning danum lulub.',
      'step2_title': 'Buksan ing Balbula ning Pamamalis (3 Minutu)',
      'step2_desc': 'Buksan ing balbula ning pamamalis, paburen yang gumanang 3 minutu, kaybat isara ya.',
      'step3_title': 'Isara ing Balbula ning Bomba at Bayuan la reng Filtro',
      'step3_desc': 'Isara ing balbula ning bomba at bayuan la ngang bayung filtro.',
      'step4_title': 'Pamlusan la reng Filtro at Tubo (1-3 Minutu)',
      'step4_desc': 'Buklat pasibayu ing balbula ning pamamalis bang pamlusayan ing duming mitagan kareng filtro at tubo kilub 1-3 minutu, kaybat isara ya pasibayu.',
      'step5_title': 'Isubli ing Agus ning Danum',
      'step5_desc': 'Isubli ing normal a agus ning danum king balbula ning gripo.',
      'important_note': 'MAHALAGANG PABALU',
      'flushing_note_desc': 'Nung ing balbula e ya makabukas, mangabaldugan a marinat ya pa ing danum at kailangan yang lisyun pa anggang luminis ya.',

      // Alerts & Notifications
      'system_alerts': 'Deng Babala ning Sistema',
      'nominal_chip': 'MASALESE',
      'active_chip': '{count} TITIPA',
      'all_systems_nominal': 'Eganaganang Sistema Masalese la',
      'no_active_alerts_desc': 'Alang aktibung babala. Ding eganaganang 3 sukat ning sensor tutugma la king pamantayan ning malinis a inuman a danum.',
      'alert_ph_acidic_title': 'Masyadung Maaslam ing Danum (Acidic pH)',
      'alert_ph_acidic_body': 'Ing pH {value} ya (Masyadung Maaslam). Ing danum maliari yang makakarawang at mala-metal.',
      'alert_ph_alkaline_title': 'Masyadung Alkaline ing Danum',
      'alert_ph_alkaline_body': 'Ing pH {value} ya (Masyadung Alkaline). Matas ing peligru ning pamipon a mineral king tubo.',
      'alert_tds_high_title': 'Matas ing Dissolved Solids (TDS)',
      'alert_tds_high_body': 'Ing TDS {value} ppm ya. Matas ing karakal da reng mineral king danum.',
      'alert_turb_high_title': 'Malabu ing Danum (High Turbidity)',
      'alert_turb_high_body': 'Ing linaw {value} NTU ya (Malabu). Matas ing peligru ning burak o latak king danum.',
      'alert_filter_replace_title': 'Kailangang Bayuan ing Filtro',
      'alert_filter_replace_body': 'Ing bie ning kekang filtro atyu king {value}%. Pakibayuan ne agad.',
      'alert_unsafe_quality_title': '🔴 E LIGTAS ING KALIDAD NING DANUM',
      'alert_unsafe_quality_body': 'Pangkabilugan a Puntos: {score}/100. Pakisuri ing kekang filtro at panibatan ning danum.',

      // Monitoring Screen
      'real_time_monitor': 'PAMANTABAY NGENI',
      'ph_trends': 'Lebel ning pH (Aslam ning Danum)',
      'tds_trends': 'Lebel ning TDS (Karakal ning Mineral)',
      'turb_trends': 'Lebel ning Turbidity (Linaw ning Danum)',
      'stability': 'TATAG',
      'avg_tds': 'KARANIWANG TDS',
      'max_turb': 'PEKAMALABU',
      'correlation_analysis': 'Pamusuri ning Pamitugma',
      'correlation_desc': 'Pabalu ning tsart ayni nung makananung mikakasabay lang magbayu ring sukat ning danum. Alimbawa, ing matas a kalabuan maralas makitugma ya king pamagbayu ning TDS o pH uli da reng dumi king danum.',
      'sensor_log_archive': 'KASALESAYAN DA RENG SUKAT',
      'tooltip_score_exp': 'Ipaliwanag ing Puntos ning Danum',
      'tooltip_view_archive': 'Lawen ing Kasalesayan',
      'tooltip_view_analysis': 'Lawen ing Pamusuri',
      'device_uptime': 'TATAG NING SISTEMA',
      'sensor_perf': 'Performance ning 3 Sensor',
      'maintenance': 'Kasalesayan ning Pamag-banlaw',

      // Reports Screen
      'filter_today': 'Ngeni',
      'filter_weekly': 'Paruminggu',
      'filter_monthly': 'Babuwan',
      'filter_all': 'Eganagana',
      'select_date': 'Mamili yang Petsa',
      'filter_today_full': 'Ngeni (Mabilug a Aldo)',
      'filter_past_7_days': 'Milabas a 7 Aldo',
      'filter_past_30_days': 'Milabas a 30 Aldo',
      'filter_all_records': 'Eganaganang Milabas a Rekord',
      'filter_custom': 'Pasadlang Pamisala',
      'records_count_suffix': 'rekord',
      'reset_filter_btn': 'I-reset',
      'data_retention_notice': 'Pabalu king Pamitagan Datos: Ding rekord a migit 6 a bulan (180 aldo) awtomatiku lang mabura bang masalese ing database.',
      'tab_telemetry': 'Sukat ning Sensor',
      'tab_audit_trail': 'Kasalesayan ning Aksyun',
      'raw_samples_count': 'MGA SUKAT ({count} BASA)',
      'session_batches_count': 'MGA GRUPU NING SUKAT ({count} SESYUN)',
      'view_batches': 'Lawen ing Grupu',
      'view_raw_logs': 'Lawen ing Isang Log',
      'no_records_found': 'Alang Rekord a Mekit',
      'no_records_desc': 'Alang datos a makatugma king pinili mung petsa at oras: {filter}',
      'reset_filter_full': 'I-reset ing Salang',
      'compliance_summary_title': 'BUOD NING PAMAMALINSUN KILINISAN',
      'pct_safe': '{pct}% LIGTAS',
      'safe_samples_summary': '{safe} kareng {total} a sukat ning sensor papatutu lang ligtas ya ing inuman a danum.',
      'show_more_records': 'Ipakita la reng Aliwang Rekord ({remaining} matitagan)',
      'tooltip_filter_date': 'Salain ing Petsa at Oras',
      'tooltip_explain_score': 'Ipaliwanag ing Puntos ning Kalidad',
      'tooltip_export_pdf': 'I-export at I-download ing PDF a Ulat',
      'export_modal_title': 'Paggawa ning Ulat at Pamag-export',
      'export_modal_subtitle': 'Mamili kategorya ning datos at format ning file bang i-print o i-download:',
      'telemetry_data': 'Datos ning Sensor ({count})',
      'audit_trail_data': 'Kasalesayan ning Aksyun ({count})',
      'all_dates_filtered': 'Eganaganang Petsa',
      'change_date': 'Bayuan ing Petsa',
      'pdf_export_options': 'DENG OPSYUN KING PAMAG-DOWNLOAD NING PDF ({count} rekord)',
      'download_save_pdf': 'I-download / I-save ing PDF ({target})',
      'print_pdf': 'I-print ing PDF ({target})',
      'report_summary_title': 'BUOD NING ULAT NING DANUM',
      'quality_score_title': 'PUNTOS NING KALIDAD',
      'averaged_metrics_title': 'KATAMTAMANG SUKAT NING SENSOR',
      'system_status_title': 'KALAGAYAN NING FILTRO AT BALBULA',
      'raw_samples_title': 'MGA SUKAT A MIKASAMA',
      'show_more_logs': 'IPAKITA DENG ALIWA PANG ULAT',
      'monthly_overview': 'PABALU NING BULAN',
      'system_perf': 'PERFORMANCE NING 3 SENSOR',
      'score': 'Lebel',
      'avg_monthly_quality': 'Karaniwang Kalidad (Bulan)',
      'avg_weekly_quality': 'Karaniwang Kalidad (Paruminggu)',

      // Profile Screen
      'account_settings': 'SETTINGS NING AKOUNT',
      'general_settings': 'Settings ning App',
      'notifications': 'Notipikasyun at Babala',
      'theme_mode': 'Itsura ning App (Theme)',
      'language': 'Amanung Gamit',
      'sys_prefs': 'Settings ning Sistema',
      'sync_interval': 'Bilis ning Pamag-update',
      'enter_name': 'Isulat ing Lagyu',
      'email_address': 'Email Address',
      'old_password': 'Dating Password',
      'new_password': 'Bayung Password',
      'confirm_new_password': 'Kumpirman ing Bayung Password',
      'update_credentials': 'Bayuan ing Password',
      'cancel_btn': 'Iurung',
      'save_changes_btn': 'I-save reng Pamagbayu',
      'logout': 'MAG-LOGOUT',
      'old_pw_required': 'Kailangan ya ing dating password',
      'new_pw_empty': 'E maliaring alang laman ing bayung password',
      'pw_not_match': 'E la mikatugma ring password',
      'profile_updated': 'Mibayu ne ing profile: {name}',
      'account_updated_success': 'Matagumpeng mibayu ing akawnt',
      'notifications_enabled_toast': 'Matagumpeng mibuklat ding notipikasyun!',
      'notifications_denied_toast': 'Tinaranggi ning sistema ing pahintulut king notipikasyun.',
      'theme_dark': 'Madalumdum (Dark)',
      'theme_light': 'Masala (Light)',
      'cloud_sync_lifetime_title': 'Bilis ning Pamag-sync king Cloud at Tagal ning Database',
      'cloud_sync_lifetime_desc': '• Nanu ya ing Pamanaus Niti:\nKukontrol nung makananu kadalas mag-upload ing sistema kareng sukat ning kalidad ning danum (pH, TDS, kalabuan, baterya) king cloud database.\n\n• Epektu king Bie ning Database at Quotas:\n• Mas Masalusu a Sync (10s): Mamie yang mabilis a sukat at mabilis a babala nung atin peligru, oneng mas dakal a kuryente at data ing gagamitan, at mas mabilis yang mitmuman ing imbakan ning database.\n• Mas Makalale a Sync (30s–60s): Magbawas king pamanulat king database, e ya agad mimitnan ing database, at mas lalong makaba ing bie ning kekang database kabang masalese pa murin ing pamantabay.',
      'app_repo_title': 'PABALU NING APP',
      'app_version': 'Bersyun 1.0.1 (Build 2)',
      'github_repo_btn': 'GitHub Repo',
      'download_apk_btn': 'I-download ing APK',
      'image_upload_soon': 'Malapit ne ing pamag-upload larawan',

      // Solar Power
      'solar_power': 'Sikad ning Aldo (Solar)',
      'battery_voltage_output': 'Lebel ning Baterya',
      'solar_charging': 'Magkarga',
      'solar_normal': 'Masalese',
      'solar_low_battery': 'Mababang Baterya',

      // UI Helpers / Educational Tooltips
      'need_to_know': 'DAPAT ABALU',
      'safe_threshold': 'Ligtas a Lebel:',
      'score_explanation_title': 'PUNTOS NING KALIDAD NING DANUM',
      'score_index_subtitle': '0 anggang 100 Lebel ning Kaligtasan at Kalinisan',
      'base_target_100': 'Pangunahing Puntos: 100 Puntos',
      'score_explanation_body': 'Magumpisa king 100 ing puntos para king masaleseng danum. Ding bawas awtomatiku lang lilitaw ibat kareng 3 sensor:',
      'rule_ph_title': '1. Pamaglayu ning pH',
      'rule_ph_desc': '-15 puntos balang 1.0 pH layu king 7.0 (Masalese: 6.5–8.5)',
      'rule_tds_title': '2. Karakal ning Mineral king TDS',
      'rule_tds_desc': '-0.1 puntos balang 1 ppm migit king 50 ppm (Masalese: < 600 ppm)',
      'rule_turb_title': '3. Kalabuan ning Danum (Turbidity)',
      'rule_turb_desc': '-10 puntos balang 1.0 NTU migit king 1.0 NTU (Masalese: < 5.0 NTU)',
      'status_tiers': 'DENG LEBEL NING KALIDAD',
      'tier_good_title': 'MAYAP / LIGTAS',
      'tier_good_desc': 'Malinis at ligtas inuman ing danum.',
      'tier_fair_title': 'KATAMTAMAN / MAG-INGAT',
      'tier_fair_desc': 'Maliari pa oneng malapit na king lebel ning kapansanan.',
      'tier_poor_title': 'E LIGTAS / DELIKADU',
      'tier_poor_desc': 'E ya ligtas ing danum! Awtomatiku yang pisara ing balbula ning danum.',
      'ph_info': 'Ing ligtas a lebel ning pH para king inuman a danum atyu king pilatan ning 6.5 at 8.5. Ding lebel a lwal kaniti maliari lang magparang kontaminasyun ning kemikal o pamangawang kareng tubo.',
      'tds_info': 'Pabalu ning TDS ing karakal da reng mineral, asin, o metal a mitunaw king danum. Ding lebel a mababa king 600 ppm maralas lang ligtas at masalese inuman.',
      'turb_info': 'Susukad ning turbidity ing kalabuan ning danum. Ing matas a kalabuan maliari yang magkanlung bakterya at magpabalu king dakal a dumi o burak king danum.',
      'score_info': 'Pangkabilugan a puntos ning kaligtasan ning danum a lilitaw ibat kareng sukat ning pH, TDS, at Turbidity sensors.',
    },
  };

  String translate(String key, [Map<String, String>? params]) {
    String text = _translations[_language]?[key] ?? _translations['English']?[key] ?? key;
    if (params != null) {
      params.forEach((paramKey, paramValue) {
        text = text.replaceAll('{$paramKey}', paramValue);
      });
    }
    return text;
  }

  bool get notificationsEnabled => _notificationsEnabled;
  String get language => _language;
  ThemeMode get themeMode => _themeMode;
  int get syncInterval => _syncInterval;
  bool get isSimulationMode => _isSimulationMode;

  Future<void> toggleSimulationMode(bool value) async {
    _isSimulationMode = value;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('simulation_mode', value);
    notifyListeners();
  }

  Future<void> toggleNotifications(bool value) async {
    _notificationsEnabled = value;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('notifications_enabled', value);
    notifyListeners();
  }

  Future<void> setLanguage(String lang) async {
    _language = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', lang);
    notifyListeners();
  }

  Future<void> setThemeMode(ThemeMode mode) async {
    _themeMode = mode;
    final prefs = await SharedPreferences.getInstance();
    String themeStr = 'dark';
    if (mode == ThemeMode.light) themeStr = 'light';
    if (mode == ThemeMode.system) themeStr = 'system';
    await prefs.setString('theme_mode', themeStr);
    notifyListeners();
  }

  Future<void> setSyncInterval(int seconds) async {
    _syncInterval = seconds;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setInt('sync_interval', seconds);
    notifyListeners();
  }
}
